**Creating a Matrix**

In [1]:
1 : 10

[1]  1  2  3  4  5  6  7  8  9 10

In [2]:
v <- 1 : 10

In [3]:
v

[1]  1  2  3  4  5  6  7  8  9 10

In [4]:
matrix(v)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [5]:
matrix(data = v, nrow = 2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [6]:
matrix(data = 1 : 12, byrow = FALSE, nrow = 4)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [7]:
matrix(data = 1:12, nrow = 4, byrow = FALSE)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12