# Creating a Matrix

In [1]:
1 : 10

[1]  1  2  3  4  5  6  7  8  9 10

In [2]:
v <- 1 : 10

In [3]:
v

[1]  1  2  3  4  5  6  7  8  9 10

In [4]:
matrix(v)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [5]:
matrix(data = v, nrow = 2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [6]:
matrix(data = 1 : 12, byrow = FALSE, nrow = 4)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [7]:
matrix(data = 1:12, nrow = 4, byrow = FALSE)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

**Creating Matrices from Vectors**

In [8]:
goog <- c(450, 451, 452, 445, 468)
msft <- c(230, 231, 232, 236, 228)

In [9]:
stocks <- c(goog, msft)

In [10]:
stock.matrix <- matrix(data = stocks, nrow = 2, byrow = TRUE)

In [11]:
stock.matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 450  451  452  445  468 
[2,] 230  231  232  236  228

**Naming Matrices**

In [12]:
days <- c('Mon', 'Tue', 'Wed', 'Thur', 'Fri')
st.names <- c('GOOG', 'MSFT')

In [13]:
colnames(x = stock.matrix) <- days
rownames(x = stock.matrix) <- st.names

In [14]:
stock.matrix

Mon Tue Wed Thur Fri
GOOG 450 451 452 445  468
MSFT 230 231 232 236  228

# Matrix Arithmetic

In [20]:
mat <- matrix(data = 1:50, byrow = TRUE, nrow = 10)

In [24]:
print(mat)
# multiplication
print(2 * mat) 
# Reciprocal
print(1 / mat)
# Division
print(mat / 2)
# power or exponent
print(mat ^ 2)

      [,1] [,2] [,3] [,4] [,5]
 [1,]    1    2    3    4    5
 [2,]    6    7    8    9   10
 [3,]   11   12   13   14   15
 [4,]   16   17   18   19   20
 [5,]   21   22   23   24   25
 [6,]   26   27   28   29   30
 [7,]   31   32   33   34   35
 [8,]   36   37   38   39   40
 [9,]   41   42   43   44   45
[10,]   46   47   48   49   50
      [,1] [,2] [,3] [,4] [,5]
 [1,]    2    4    6    8   10
 [2,]   12   14   16   18   20
 [3,]   22   24   26   28   30
 [4,]   32   34   36   38   40
 [5,]   42   44   46   48   50
 [6,]   52   54   56   58   60
 [7,]   62   64   66   68   70
 [8,]   72   74   76   78   80
 [9,]   82   84   86   88   90
[10,]   92   94   96   98  100
            [,1]       [,2]       [,3]       [,4]       [,5]
 [1,] 1.00000000 0.50000000 0.33333333 0.25000000 0.20000000
 [2,] 0.16666667 0.14285714 0.12500000 0.11111111 0.10000000
 [3,] 0.09090909 0.08333333 0.07692308 0.07142857 0.06666667
 [4,] 0.06250000 0.05882353 0.05555556 0.05263158 0.05000000
 [5,] 0.04761

**Comparison operators with matrices**

In [26]:
print(mat > 17)

       [,1]  [,2]  [,3]  [,4]  [,5]
 [1,] FALSE FALSE FALSE FALSE FALSE
 [2,] FALSE FALSE FALSE FALSE FALSE
 [3,] FALSE FALSE FALSE FALSE FALSE
 [4,] FALSE FALSE  TRUE  TRUE  TRUE
 [5,]  TRUE  TRUE  TRUE  TRUE  TRUE
 [6,]  TRUE  TRUE  TRUE  TRUE  TRUE
 [7,]  TRUE  TRUE  TRUE  TRUE  TRUE
 [8,]  TRUE  TRUE  TRUE  TRUE  TRUE
 [9,]  TRUE  TRUE  TRUE  TRUE  TRUE
[10,]  TRUE  TRUE  TRUE  TRUE  TRUE
