**Creating a Matrix**

In [1]:
1 : 10

[1]  1  2  3  4  5  6  7  8  9 10

In [2]:
v <- 1 : 10

In [3]:
v

[1]  1  2  3  4  5  6  7  8  9 10

In [4]:
matrix(v)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [5]:
matrix(data = v, nrow = 2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [6]:
matrix(data = 1 : 12, byrow = FALSE, nrow = 4)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [7]:
matrix(data = 1:12, nrow = 4, byrow = FALSE)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

**Creating Matrices from Vectors**

In [8]:
goog <- c(450, 451, 452, 445, 468)
msft <- c(230, 231, 232, 236, 228)

In [9]:
stocks <- c(goog, msft)

In [10]:
stock.matrix <- matrix(data = stocks, nrow = 2, byrow = TRUE)

In [11]:
stock.matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 450  451  452  445  468 
[2,] 230  231  232  236  228

**Naming Matrices**

In [12]:
days <- c('Mon', 'Tue', 'Wed', 'Thur', 'Fri')
st.names <- c('GOOG', 'MSFT')

In [13]:
colnames(x = stock.matrix) <- days
rownames(x = stock.matrix) <- st.names

In [14]:
stock.matrix

Mon Tue Wed Thur Fri
GOOG 450 451 452 445  468
MSFT 230 231 232 236  228